version: '3.3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
  nginx:
    container_name: foodgram-proxy
    build: ./infra/
    ports:
      - "7000:80"
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - frontend
      - backend