# Generated by Django 3.2.3 on 2025-01-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ('original_url',), 'verbose_name': 'Короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
    ]
