# Generated by Django 3.2.3 on 2025-01-09 22:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'abstract': False,
                'default_related_name': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название ингредиента', max_length=128, unique=True, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Введите единицу измерения', max_length=64, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name',),
                'default_related_name': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумайте название для рецепта', max_length=256, verbose_name='Название')),
                ('text', models.TextField(help_text='Опишите последовательность действий', verbose_name='Текстовое описание рецепта')),
                ('cooking_time', models.PositiveSmallIntegerField(default=1, help_text='Укажите время приготовления блюда в минутах', validators=[django.core.validators.MinValueValidator(1, 'Любой рецепт требует как минимум 1-й минуты!'), django.core.validators.MaxValueValidator(1440, 'Вы наверное ошиблись? Время пригтовления блюда должно быть менее суток!')], verbose_name='Время приготовления')),
                ('image', models.ImageField(help_text='Загрузите подходящее фото блюда', upload_to='recipes/', verbose_name='Фото блюда')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время публикации рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-pub_date'],
                'default_related_name': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Укажите количество ингредиента в рецепте', validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиента в рецепте должно быть равно хотя бы 1, и не превышать значение 20000 единиц'), django.core.validators.MaxValueValidator(20000, 'Количество ингредиента в рецепте должно быть равно хотя бы 1, и не превышать значение 20000 единиц')], verbose_name='Количество ингредиента в рецепте')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингредиенты в рецепте',
                'ordering': ('recipe',),
                'default_related_name': 'ingredients_in_recipe',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название тега', max_length=32, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(help_text='Укажите слаг тега', max_length=32, unique=True, verbose_name='Уникальный слаг тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglists', to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
                'abstract': False,
                'default_related_name': 'shoppinglists',
            },
        ),
    ]
